services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    # env_file: docker-compose.env
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
      # - 8081:8081
    profiles: 
      - chat
      - prod
      - dev
      - model

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # env_file: docker-compose.env
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - model_loader
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    profiles: 
      - chat

  model_loader:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    # env_file: "docker-compose.env"
    environment:
      LOCAL_LLM: ${LOCAL_LLM:-llama3}
    command: >
      sh -c '
        until curl -s -f http://ollama:11434/; do
          echo "Waiting for ollama..."; sleep 2;
        done &&
        curl -s http://ollama:11434/api/pull -d "{\"name\": \"${LOCAL_LLM}\"}"
      '
    depends_on:
      - ollama
    restart: "no"
    profiles: 
      - chat
      - prod
      - dev
      - model

  tussler:
    image: tussler:latest
    # env_file: docker-compose.env
    ports:
      - 8081:8081
    depends_on:
      - model_loader
      # - open-webui
    environment:
      - ENV=${ENV:-production} 
    command: > 
      sh -c "uvicorn tussler.launcher:app --host 0.0.0.0 --port 8081"

    # command: >
    #   sh -c "if [ "$ENV" = "development" ]; then
    #     uvicorn main:app --host 0.0.0.0 --port 8081 --reload
    #   else
    #     uvicorn main:app --host 0.0.0.0 --port 8081
    #   fi"
    restart: unless-stopped
    profiles: 
      - prod 

  tussler-dev:
    build:
      context: .
      dockerfile: tussler.Dockerfile
    # env_file: docker-compose.env
    # network_mode: "service:ollama"
    ports:
      - 8081:8081
    depends_on:
      - model_loader
      # - open-webui
    volumes:
      - .:/app
    environment:
      - ENV=${ENV:-production}
      # - OLLAMA_HOST=http://ollama:11434
      # - OLLAMA_BASE_URL=http://ollama:11434
    # command: >
    #   sh -c "uvicorn tussler.launcher:app --host 0.0.0.0 --port 8081 --reload"
    command: sleep infinity
    restart: unless-stopped
    profiles: 
      - dev

volumes:
  ollama: {}
  open-webui: {}