[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=5

[program:jupyter]
command=python3 -m notebook --ip=0.0.0.0 --no-browser --NotebookApp.token=''
directory=/app
stdout_logfile=/var/log/jupyter.log
stderr_logfile=/var/log/jupyter_err.log
autostart=true
autorestart=true
startsecs=5

[program:uvicorn]
command=uvicorn main:app --host 0.0.0.0 --port 8081
directory=/app
stdout_logfile=/var/log/uvicorn.log
stderr_logfile=/var/log/uvicorn_err.log
autostart=true
autorestart=true
startsecs=5
